name: Build and deploy Laravel to Azure Web App - laravelnewtestforbootcamp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, pdo_mysql, intl
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Laravel optimizations
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9BE029C7FBF84E1BA9498F407A5754FC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BB52E7F4A02C4354BC63A3F6C91D241A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F7B108C367DD43EEB7BA9D22F3648F0D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'laravelnewtestforbootcamp'
          slot-name: 'Production'
          package: .

      # Optional: run migrations after deployment
      - name: Run Laravel migrations
        run: |
          cd /home/site/wwwroot
          php artisan migrate --force
        shell: bash
